OAUTH2_SERVER_URL: http://localhost:9191
REALM_URL: ${OAUTH2_SERVER_URL}/realms/book-store

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${REALM_URL}/protocol/openid-connect/certs
          issuer-uri: ${REALM_URL}
