name: book-list Service

on:
  push:
    paths:
      - booklist-service/**
    branches:
      - '**'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      working-directory: ./booklist-service
    defaults:
      run:
        working-directory: ${{ env.working-directory }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with maven
        run: ./mvnw -ntp verify
      - if: ${{ github.ref == 'refs/heads/master'}}
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - if: ${{ github.ref == 'refs/heads/master'}}
        name: Build and publish Docker image
        run: |
          ./mvnw spring-boot:build-image -DskipTests
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/booklist-service